# Generated by Django 4.2.1 on 2023-05-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misclientportal', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('repair', 'Repair/Troubleshoot'), ('software', 'Software Installation'), ('formatting', 'Formatting'), ('network', 'Network Connectivity'), ('internet', 'Internet Service'), ('other', 'Others')], max_length=20)),
                ('scheduled_response_date', models.DateField()),
                ('scheduled_response_time', models.TimeField()),
                ('verified_by_client', models.BooleanField()),
                ('problem_found', models.TextField()),
                ('recommendation', models.TextField()),
                ('service_completed_date', models.DateField()),
                ('service_verified_by_client_date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misclientportal.appointment')),
            ],
        ),
    ]
